services:
  postgres:
    image: postgres:15
    container_name: postgres_test_purge
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - C:\yao\myWorkspace\docker\postgres_test_purge\postgres_data:/var/lib/postgresql/data
